import React, { useState, useEffect, useRef } from 'react';
import PropTypes from 'prop-types';
import SelectedTextHandler from './selectedTextHandler';
import './ChatbotWidget.css';

const ChatbotWidget = ({ apiUrl = 'http://localhost:8000/api/v1' }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId, setSessionId] = useState(null);
  const messagesEndRef = useRef(null);

  // Initialize session and selected text handler on component mount
  useEffect(() => {
    // Generate a session ID if one doesn't exist
    if (!sessionId) {
      const storedSessionId = localStorage.getItem('chatbot_session_id');
      if (storedSessionId) {
        setSessionId(storedSessionId);
      } else {
        const newSessionId = generateSessionId();
        localStorage.setItem('chatbot_session_id', newSessionId);
        setSessionId(newSessionId);
      }
    }

    // Initialize selected text handler
    const selectedTextHandler = new SelectedTextHandler(apiUrl, setMessages, setIsLoading, sessionId);
    selectedTextHandler.init();

    // Cleanup function
    return () => {
      selectedTextHandler.destroy();
    };
  }, [sessionId, apiUrl]);

  // Scroll to bottom of messages
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const generateSessionId = () => {
    return 'session_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
  };

  const sendMessage = async (message) => {
    if (!message.trim() || isLoading) return;

    // Add user message to chat
    const userMessage = {
      id: Date.now(),
      text: message,
      sender: 'user',
      timestamp: new Date().toISOString()
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);

    try {
      // Call the backend API
      const response = await fetch(`${apiUrl}/chat`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          query: message,
          session_id: sessionId
        })
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();

      // Update session ID if it was generated by the backend
      if (data.session_id && data.session_id !== sessionId) {
        setSessionId(data.session_id);
        localStorage.setItem('chatbot_session_id', data.session_id);
      }

      // Add bot response to chat
      const botMessage = {
        id: Date.now() + 1,
        text: data.response,
        sender: 'bot',
        sources: data.sources || [],
        confidence: data.confidence,
        timestamp: data.timestamp || new Date().toISOString()
      };

      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      console.error('Error sending message:', error);

      // Add error message to chat
      const errorMessage = {
        id: Date.now() + 1,
        text: 'Sorry, I encountered an error processing your request. Please try again.',
        sender: 'bot',
        isError: true,
        timestamp: new Date().toISOString()
      };

      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSendMessage = (e) => {
    e.preventDefault();
    sendMessage(inputValue);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage(inputValue);
    }
  };

  const toggleChat = () => {
    setIsOpen(!isOpen);
  };

  const clearChat = () => {
    setMessages([]);
  };

  return (
    <div className="chatbot-widget">
      {isOpen ? (
        <div className="chatbot-container">
          <div className="chatbot-header">
            <div className="chatbot-title">Physical AI Assistant</div>
            <div className="chatbot-actions">
              <button
                className="chatbot-clear-btn"
                onClick={clearChat}
                title="Clear chat"
              >
                ✕
              </button>
              <button
                className="chatbot-close-btn"
                onClick={toggleChat}
                title="Close chat"
              >
                −
              </button>
            </div>
          </div>

          <div className="chatbot-messages">
            {messages.length === 0 ? (
              <div className="chatbot-welcome">
                <p>Hello! I'm your Physical AI & Humanoid Robotics assistant.</p>
                <p>Ask me anything about the book content:</p>
                <ul>
                  <li>• Concepts in Physical AI</li>
                  <li>• ROS 2 development</li>
                  <li>• Humanoid robotics</li>
                  <li>• Vision-language-action systems</li>
                </ul>
              </div>
            ) : (
              messages.map((message) => (
                <div
                  key={message.id}
                  className={`chatbot-message ${message.sender}-message`}
                >
                  <div className="message-content">
                    <div className="message-text">{message.text}</div>
                    {message.sources && message.sources.length > 0 && (
                      <div className="message-sources">
                        <details>
                          <summary>Sources</summary>
                          <ul>
                            {message.sources.map((source, index) => (
                              <li key={index}>{source}</li>
                            ))}
                          </ul>
                        </details>
                      </div>
                    )}
                    {message.confidence !== undefined && (
                      <div className="message-confidence">
                        Confidence: {(message.confidence * 100).toFixed(1)}%
                      </div>
                    )}
                    {message.isError && (
                      <div className="message-error">
                        Error occurred - please try again
                      </div>
                    )}
                  </div>
                </div>
              ))
            )}
            {isLoading && (
              <div className="chatbot-message bot-message">
                <div className="message-content">
                  <div className="message-text">
                    <span className="typing-indicator">
                      <span></span>
                      <span></span>
                      <span></span>
                    </span>
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <form className="chatbot-input-form" onSubmit={handleSendMessage}>
            <textarea
              className="chatbot-input"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask about Physical AI & Humanoid Robotics..."
              rows="1"
              disabled={isLoading}
            />
            <button
              type="submit"
              className="chatbot-send-btn"
              disabled={isLoading || !inputValue.trim()}
            >
              Send
            </button>
          </form>
        </div>
      ) : (
        <button className="chatbot-toggle-btn" onClick={toggleChat}>
          <span className="chatbot-icon">🤖</span>
          <span className="chatbot-label">AI Assistant</span>
        </button>
      )}
    </div>
  );
};

ChatbotWidget.propTypes = {
  apiUrl: PropTypes.string
};

export default ChatbotWidget;