import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for Physical AI and Humanoid Robotics book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      collapsed: false,
      items: [
        'intro',
        {
          type: 'category',
          label: 'Part I: Foundations of Physical AI',
          collapsed: false,
          items: [
            'intro-to-physical-ai/intro-to-physical-ai',
            'intro-to-physical-ai/embodied-intelligence',
            'intro-to-physical-ai/sensor-systems',
          ],
        },
        {
          type: 'category',
          label: 'Part II: ROS 2 — The Robotic Nervous System',
          collapsed: false,
          items: [
            'ros-2-fundamentals/ros-2-architecture',
            'ros-2-fundamentals/nodes-topics-services',
            'ros-2-fundamentals/building-ros-packages',
            'ros-2-fundamentals/urdf-robot-description',
            'ros-2-fundamentals/jetson-deployment-guide',
            'ros-2-fundamentals/sensor-data-processing',
            'ros-2-fundamentals/troubleshooting-ros2',
          ],
        },
        {
          type: 'category',
          label: 'Part III: Simulation & Digital Twins',
          collapsed: false,
          items: [
            'gazebo-simulation/setting-up-gazebo',
            'gazebo-simulation/urdf-sdf-simulation-files',
            'gazebo-simulation/unity-robot-visualization',
            'gazebo-simulation/sensor-simulation',
          ],
        },
        {
          type: 'category',
          label: 'Part IV: NVIDIA Isaac Platform',
          collapsed: false,
          items: [
            'nvidia-isaac/introduction-to-isaac-sim',
            'nvidia-isaac/synthetic-data-generation',
            'nvidia-isaac/isaac-ros-perception',
            'nvidia-isaac/navigation-path-planning',
          ],
        },
        {
          type: 'category',
          label: 'Part V: Humanoid Robotics Development',
          collapsed: false,
          items: [
            'humanoid-development/kinematics-dynamics',
            'humanoid-development/bipedal-locomotion',
            // 'humanoid-development/manipulation',              // TODO: Add this document
            // 'humanoid-development/human-robot-interaction', // TODO: Add this document
          ],
        },
        {
          type: 'category',
          label: 'Part VI: Vision-Language-Action Systems',
          collapsed: false,
          items: [
            'vision-language-action/whisper-speech-input',
            'vision-language-action/llm-cognitive-planning',
            'vision-language-action/multi-modal-interaction',
            'vision-language-action/natural-language-to-ros-action',
            'vision-language-action/example-implementations',
          ],
        },
        {
          type: 'category',
          label: 'Part VII: Capstone Project: Autonomous Humanoid',
          collapsed: false,
          items: [
            'capstone-humanoid-project/system-architecture',
            'capstone-humanoid-project/mapping-environment',
            'capstone-humanoid-project/ros2-integration',
            'capstone-humanoid-project/voice-command-processing',
            'capstone-humanoid-project/cognitive-planning',
            'capstone-humanoid-project/object-detection-pipeline',
            'capstone-humanoid-project/navigation-obstacle-avoidance',
            'capstone-humanoid-project/manipulation-task',
            'capstone-humanoid-project/full-pipeline',
          ],
        },
        {
          type: 'category',
          label: 'Part VIII: Hardware & Development Infrastructure',
          collapsed: false,
          items: [
            'hardware-requirements/index',
            'hardware-requirements/hardware-architecture',
            'tools-lab-setup/index',
            'tools-lab-setup/lab-setup-options',
            'unity-integration/index',
            'unity-integration/unity-robotics-integration',
          ],
        },
        {
          type: 'category',
          label: 'Part IX: Reference Materials',
          collapsed: false,
          items: [
            'glossary/index',
            'assessments/index',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
